language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- echo 'No tests yet. yolo.'
notifications:
  irc: 
    secure: VNUGqBXIFZvtX7Lf3H0bDt9vkBHS42tMSDAGZevWvh1vmfQfgmyJI0ZRvV5KkwK6gROQjK0ZGL9vB0BGOvCPEinwzETkwMQPgyI/670DVY1i50V8nH/VB7IgDF+9GhkY24tfJTAodHYpdhFl4hf2eke0F+aaxtFqZHt3NAaIwf99blM4P54d6LRHMIPj/MB72tAulXERoQ3nSkWPW9iA5h4KRC19e8JtmMyHxX0mTVJYIgu9CeLNTaoEV1rrKTcrJUYpA6Ea1PXkO2jC7EdMTEayM5pcaVhMcyYk7ddCKyz9N1YyPI6cbc5dr/FNzu1jKdDsX5d8xApIPPcInnMslGkHnGaMBKdc4sznABWBZa680NAPAx/oj9aWDRk/iXLnWeNwtUKLIJSuk9TCi+1UFJH/UisJR5lQiycbz3D8K53HdFKeWyGjANqwzKwH8esVfz2rO3uC33w9ZYX0Aaa5wJqZXwBmnEO5mVdJGpnCjp1G/yOYrnwbCEHc1RnVXcawVhtMiIAi6QMxN+z47L4KFTD38AfRyyBLcUOrBs+IqNfCJw7WMVKi0bObUkLGo0243WfjzecLPlp12bADaNK+7Mky8omKz6qgiyNBtp2bRt/BzN5hUBQUxdnRrfKYnAUU3xqcPw/C2K18tQgh1Fff3XTiNy/yvhWD9iCnFZeXeu8=
